name: Build iOS Unsigned
on:
  workflow_dispatch: # กดสั่งรันเองได้

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: git add .actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd TranslateApp
          npm install

      - name: Install Pods
        run: |
          cd TranslateApp/ios
          pod install

      - name: Build Xcode Project
        run: |
          cd TranslateApp/ios
          xcodebuild -workspace TranslateApp.xcworkspace \
                     -scheme TranslateApp \
                     -configuration Debug \
                     -sdk iphoneos \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_ING_REQUIRED=NO \
                     CODE_SIGN_ENTITLEMENTS="" \
                     CODE_SIGNING_METHOD=manual \
                     clean build
